name: "hello workflow"
on:
  push:
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "hello world"
        run: echo "Hello world"

      - name: "Test project"
        run: |
          echo: "Testing"
          echo: ""